# Numpy

# To create array

In [1]:
import numpy as np

In [2]:
my_list=[2,3,4,5,6]
array=np.array(my_list)

In [3]:
array

array([2, 3, 4, 5, 6])

In [4]:
print(array)

[2 3 4 5 6]


In [5]:
type(array)

numpy.ndarray

In [6]:
array.shape

(5,)

# To reshape an array

In [7]:
my_list1=[2,4,5,6,7]
my_list2=[6,7,4,6,2]
my_list3=[9,0,4,2,5]
array1=np.array([my_list1,my_list2,my_list3])

In [8]:
print(array1)

[[2 4 5 6 7]
 [6 7 4 6 2]
 [9 0 4 2 5]]


In [9]:
array1.shape

(3, 5)

In [10]:
array1.reshape(5,3) 

array([[2, 4, 5],
       [6, 7, 6],
       [7, 4, 6],
       [2, 9, 0],
       [4, 2, 5]])

# Indexing

In [11]:
array

array([2, 3, 4, 5, 6])

In [12]:
array[3]

5

In [13]:
array[:3]

array([2, 3, 4])

In [14]:
array[:-2]

array([2, 3, 4])

In [15]:
array[1:3]

array([3, 4])

In [16]:
array1

array([[2, 4, 5, 6, 7],
       [6, 7, 4, 6, 2],
       [9, 0, 4, 2, 5]])

In [17]:
array1[ :,:]

array([[2, 4, 5, 6, 7],
       [6, 7, 4, 6, 2],
       [9, 0, 4, 2, 5]])

In [18]:
array1[ 1:,1:]

array([[7, 4, 6, 2],
       [0, 4, 2, 5]])

In [19]:
array1[ :2,:3]

array([[2, 4, 5],
       [6, 7, 4]])

# Arange

In [20]:
array2=np.arange(1,11)

In [21]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
array3=np.arange(3,17,2)

In [23]:
array3

array([ 3,  5,  7,  9, 11, 13, 15])

# Linspace

In [24]:
#To print equally spaced numbers between two given numbers
np.linspace(1,15,6)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])

# Copy

In [25]:
array4=np.array([1,2,3,4,5,6,7,8,9])

In [26]:
array4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array4[3:]=200

In [28]:
array4

array([  1,   2,   3, 200, 200, 200, 200, 200, 200])

In [29]:
array5=array4

In [30]:
array5

array([  1,   2,   3, 200, 200, 200, 200, 200, 200])

In [31]:
array5[3:]=600

In [32]:
array5

array([  1,   2,   3, 600, 600, 600, 600, 600, 600])

In [33]:
array4

array([  1,   2,   3, 600, 600, 600, 600, 600, 600])

In [34]:
#Use copy inorder to avoid above problem
array6=np.array([1,2,3,4,5])

In [35]:
array6

array([1, 2, 3, 4, 5])

In [36]:
array7=array6.copy()

In [37]:
array7

array([1, 2, 3, 4, 5])

In [38]:
array7[:3]=200

In [39]:
print(array7)
print(array6)

[200 200 200   4   5]
[1 2 3 4 5]


In [40]:
array6

array([1, 2, 3, 4, 5])

# Create array and reshape

In [41]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Ones, random

In [42]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.random.rand(4)

array([0.60727843, 0.5609106 , 0.40877871, 0.7179296 ])

In [44]:
np.random.rand(3,4)

array([[0.18970519, 0.72165068, 0.79535144, 0.23853563],
       [0.51301232, 0.91518332, 0.98856754, 0.30191477],
       [0.7053901 , 0.19713369, 0.6047598 , 0.67111238]])

In [45]:
np.random.randn(3,4)

array([[ 1.21447137,  0.25530114,  1.24620381, -0.85103147],
       [-0.34094663,  0.97502589, -0.16432838, -1.12285907],
       [ 0.43918009, -1.23911819, -1.27680888, -1.1749785 ]])

In [46]:
#To print 10 random integer numbers between 2 and 15
np.random.randint(2,15,10)

array([ 8,  8, 10,  5,  8,  6, 10, 14, 12,  9])

In [47]:
#To reshape above items
np.random.randint(2,15,10).reshape(5,2)

array([[13, 14],
       [ 7,  7],
       [ 7,  5],
       [ 7, 12],
       [ 7,  3]])

In [48]:
#To print elements between 0 and 1
np.random.random_sample(2)

array([0.94977752, 0.26565232])

In [49]:
np.random.random_sample((2,3))

array([[0.31087513, 0.47833306, 0.1238315 ],
       [0.34729188, 0.01442153, 0.0447085 ]])